# Generated by Django 4.2.7 on 2025-10-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
