# Generated by Django 5.2.7 on 2025-10-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_name_alter_categories_slug_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name_plural': 'Продукти'},
        ),
    ]
